default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci(force: true)
    
    if is_ci
      increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"], xcodeproj: "RoleVault.xcodeproj")
    else
      increment_build_number(xcodeproj: "RoleVault.xcodeproj")
    end
    
    match(type: "appstore", readonly: true)
    
    build_app(
      scheme: "RoleVault",
      configuration: "Release",
      export_method: "app-store"
    )
    
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
