default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    ensure_git_status_clean

    increment_build_number(xcodeproj: "RoleVault.xcodeproj")

    build_app(
      scheme: "RoleVault",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      output_directory: "build"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      notify_external_testers: false
    )
  end

  desc "Build local debug IPA"
  lane :build_debug do
    build_app(
      scheme: "RoleVault",
      export_method: "development",
      configuration: "Debug",
      output_directory: "build"
    )
  end
end
