default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci(force: true)
    
    increment_build_number(xcodeproj: "RoleVault.xcodeproj")
    
    match(type: "appstore", readonly: true)
    
    build_app(
      scheme: "RoleVault",
      export_method: "app-store"
    )
    
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
